name: "Tests"

on: [push, pull_request]

jobs:
  prepare:
    runs-on: ubuntu-latest
    container: node:14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    - name: Set up Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

  run-tests:
    runs-on: ubuntu-latest
    container: node:14
    needs: prepare

    steps:
    - name: Run Typescript tests
      run: npm run test-tsc

    - name: Run Library tests
      run: npm run test

    - name: Run Library benchmark tests
      run: npm run benchmark-michijs

    - name: Run Library benchmark with map tests
      run: npm run benchmark-michijs-map 

    - name: Run Vanilla benchmark tests
      run: npm run benchmark-vanilla
